import type { NextPage } from 'next'
import Head from 'next/head'
import WalletConnect from '../components/WalletConnect'
import { useStoreActions, useStoreState } from "../utils/store"
import Link from 'next/link'
import { useState, useEffect } from 'react'

const Home: NextPage = () => {
  const walletStore = useStoreState((state: any) => state.wallet)
  const [nftList, setNftList] = useState([])

  useEffect(() => {
    //const lucid = initLucid(walletStore.name)
    console.log(walletStore.address)
  }, [walletStore.address])

  return (
    <div className="px-0">
      <Head>
        <title>Cardano subscription manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hero min-h-screen bg-base-200">
        <div className="hero-content flex-col ">
          <div className="card flex-shrink-0 w-full max-w-lg shadow-2xl bg-base-100">
            <div className="card-body">
              <div className="text-center">
                <h1 className="text-3xl font-bold">Subscription manager</h1>
                <p className="py-4 break-all max-w-fit">Connect your wallet and select an option below.</p>
                <WalletConnect />
                <div className="my-10 text-center">
                  <Link href="/create">
                    <button className="btn btn-primary m-5 w-40" >Create subscription</button>
                  </Link>
                  <Link href="/vendor">
                    <button className="btn btn-primary m-5 w-40" >View subscribers (as vendor)</button>
                  </Link>
                  <Link href="/customer">
                    <button className="btn btn-primary m-5 w-40" >View active subscriptions (as customer)</button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
export default Home
