import type { NextPage } from 'next'
import Head from 'next/head'
import { useStoreActions, useStoreState } from "../utils/store"
import Link from 'next/link'
import { useState, useEffect } from 'react'

const Home: NextPage = () => {
  const walletStore = useStoreState((state: any) => state.wallet)

  return (
    <div className="px-0">
      <Head>
        <title>Cardano minting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hero min-h-screen bg-base-200">
        <div className="hero-content flex-col ">
        </div>
      </div>
    </div>
  )
}
export default Home
